// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop.DiscountAPI.Context;

#nullable disable

namespace Shop.DiscountAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105114710_InitialCoupon")]
    partial class InitialCoupon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop.DiscountAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83212972-ae1d-424c-a65f-b0033be942f6"),
                            CouponCode = "WELCOME10",
                            CreatedAt = new DateTime(2026, 1, 5, 11, 47, 10, 519, DateTimeKind.Utc).AddTicks(7961),
                            DiscountAmount = 10.00m,
                            ExpiryDate = new DateTime(2026, 2, 5, 11, 47, 10, 519, DateTimeKind.Utc).AddTicks(8085)
                        },
                        new
                        {
                            Id = new Guid("5c656c3f-2b59-4209-836f-9bf53516de0e"),
                            CouponCode = "SUMMER15",
                            CreatedAt = new DateTime(2026, 1, 5, 11, 47, 10, 519, DateTimeKind.Utc).AddTicks(8428),
                            DiscountAmount = 15.00m,
                            ExpiryDate = new DateTime(2026, 3, 5, 11, 47, 10, 519, DateTimeKind.Utc).AddTicks(8429)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
