// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.ProductAPI.Context;

#nullable disable

namespace Shop.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Shop.ProductAPI.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3576bc6e-b2a4-481a-88c5-8409559c1083"),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("398a9c26-1884-417f-ba22-33405e67f08b"),
                            Name = "Watches"
                        });
                });

            modelBuilder.Entity("Shop.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<long>("Stock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("199184ab-3630-4f3c-8232-44a2bf9ac5b5"),
                            CategoryId = new Guid("3576bc6e-b2a4-481a-88c5-8409559c1083"),
                            Description = "Just a book",
                            ImageUrl = "",
                            Name = "The persue of hapiness",
                            Price = 9.99m,
                            Stock = 111L
                        },
                        new
                        {
                            Id = new Guid("1f13c916-dd5d-4fe9-808d-c662917d6c5b"),
                            CategoryId = new Guid("398a9c26-1884-417f-ba22-33405e67f08b"),
                            Description = "Just a watch",
                            ImageUrl = "",
                            Name = "Seiko 1",
                            Price = 999m,
                            Stock = 111L
                        });
                });

            modelBuilder.Entity("Shop.ProductAPI.Models.Product", b =>
                {
                    b.HasOne("Shop.ProductAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.ProductAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
