// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop.CartAPI.Context;

#nullable disable

namespace Shop.CartAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop.CartAPI.Models.CartHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CartHeaders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b6d1249-7e5c-4ce0-b910-ec96bbee5ac3"),
                            CouponCode = "DISC123",
                            UserId = new Guid("01c3d0c8-3e3c-421c-b19d-c53d0bc751e5")
                        });
                });

            modelBuilder.Entity("Shop.CartAPI.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartHeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee45e77b-2248-4e3a-bcea-b0e16a297e4b"),
                            CartHeaderId = new Guid("0b6d1249-7e5c-4ce0-b910-ec96bbee5ac3"),
                            ProductId = new Guid("199184ab-3630-4f3c-8232-44a2bf9ac5b5"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Shop.CartAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<long>("Stock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("199184ab-3630-4f3c-8232-44a2bf9ac5b5"),
                            CategoryName = "",
                            Description = "Just a book",
                            ImageUrl = "",
                            Name = "The persue of hapiness",
                            Price = 9.99m,
                            Stock = 111L
                        },
                        new
                        {
                            Id = new Guid("1f13c916-dd5d-4fe9-808d-c662917d6c5b"),
                            CategoryName = "",
                            Description = "Just a watch",
                            ImageUrl = "",
                            Name = "Seiko 1",
                            Price = 999m,
                            Stock = 111L
                        });
                });

            modelBuilder.Entity("Shop.CartAPI.Models.CartItem", b =>
                {
                    b.HasOne("Shop.CartAPI.Models.CartHeader", "CartHeader")
                        .WithMany("CartItems")
                        .HasForeignKey("CartHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.CartAPI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.CartAPI.Models.CartHeader", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Shop.CartAPI.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
